export { default as Home } from './home'
export { default as Login } from './auth'
export { default as UserProfile } from './user'
export { default as Modules } from './modules'
export { default as Module } from './modul'